### ISSUE TITLE
Please update the format used for build config imports on Travis CI

### ISSUE THREAD

**Issue by svenfuchs** [rust-lang-ru/async-book#79]
I am opening this issue here to raise the right people's attention. Please see https://github.com/rust-lang/simpleinfra/issues/33 for details.

**Comment by funkill** [comment]
Thank you for reporting this!

We don’t use Travis CI for this repository. We have copy of `rust-lang/async-book` what has Travis config for simplify translation of this book. After fixing it in `rust-lang/async-book` we have new config in some days.
